expr_name: test
log_dir: ./logs             #log directory
seed: 0
device_num: 1

Environment:
  Entities:
    - entity_name: 'government'
      entity_args:
        n: 1            #number of government
#        tau: 0.263
#        xi: 0.049
#        tau_a: 0
#        xi_a: 0
#        Gt_prob: 0.189
#        G_scale: 10
        action_shape: 6

    - entity_name: 'household'
      entity_args:
        n: 100
        consumption_range: 1
        working_hours_range: 24
        CRRA: 1
        IFE: 2
        eta: 0
        action_shape: 2
#        WageRate: 1
#        RentRate: 0.04
        e_p: 2.2e-6
        e_q: 0.990
        rho_e: 0.982
        sigma_e: 0.200
        super_e: 504.3

  env_core:
    possible_agents: ['government', 'households']
    env_args:
      alpha: 1/3
#      WageRate: 1
#      RentRate: 0.04
      episode_years: 100
      year_per_step: 1
      depreciation_rate: 0.06
      consumption_tax_rate: 0.065
      interest_rate: 0.04
      hours_max: 283720               # 7093 * 40
      gini_weight: 1


Trainer:
  n_households: 100
  log_std_min:  -20
  log_std_max:  2
  hidden_size:  256
  cuda: True
  q_lr: 3e-4
  p_lr: 3e-4
  buffer_size:  1e6
  env_name: 'wealth_distribution'
  init_exploration_policy:  'gaussian'
  n_epochs: 1000
  epoch_length: 1000
  update_cycles:  10
  target_update_interval: 1
  display_interval: 1
  batch_size: 64
  gamma: 0.975
  tau:  5e-3
  eval_episodes: 10
  init_exploration_steps: 1000
  ppo_tau: 0.95
  ppo_gamma: 0.99
  eps: 1e-5
  update_epoch: 10
  clip: 0.1
  vloss_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5
  update_freq: 100
  initial_train: 2000









