wandb_version: 1

_content:
  desc: null
  value:
    batch_size: '64'
    buffer_size: '1000000.0'
    cuda: 'True'
    display_interval: '1'
    env_name: wealth_distribution
    epoch_length: '1000'
    eval_episodes: '10'
    gamma: '0.99'
    hidden_size: '256'
    init_exploration_policy: '1000.0'
    init_exploration_steps: '1000'
    log_std_max: '2'
    log_std_min: '-20'
    n_epochs: '3000'
    n_households: '100'
    p_lr: '0.0003'
    q_lr: '0.0003'
    target_update_interval: '1'
    tau: '0.005'
    update_cycles: '10'
_flags_cache:
  desc: null
  value:
    struct: null
_metadata:
  desc: null
  value: ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True,
    key='Trainer', flags={}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>,
    {}), key_type=typing.Any, element_type=typing.Any)
_parent:
  desc: null
  value: '{''expr_name'': ''test'', ''log_dir'': ''./logs'', ''seed'': 0, ''Environment'':
    {''Entities'': [{''entity_name'': ''government'', ''entity_args'': {''n'': 1,
    ''tau'': 0.5, ''xi'': 0.2, ''tau_a'': 0.02, ''xi_a'': 0, ''G'': 0, ''observation_shape'':
    6, ''action_shape'': 5}}, {''entity_name'': ''household'', ''entity_args'': {''n'':
    100, ''consumption_range'': 1, ''working_hours_range'': 24, ''CRRA'': 2.0, ''IFE'':
    0.6, ''eta'': 0, ''lump_sum_transfer'': 0.0001, ''observation_shape'': 13, ''action_shape'':
    2}}], ''env_core'': {''possible_agents'': [''government'', ''households''], ''env_args'':
    {''alpha'': ''1/3'', ''WageRate'': 1, ''RentRate'': 0.04, ''episode_years'': 100,
    ''year_per_step'': 1}}}, ''Trainer'': {''n_households'': 100, ''log_std_min'':
    -20, ''log_std_max'': 2, ''hidden_size'': 256, ''cuda'': True, ''q_lr'': 0.0003,
    ''p_lr'': 0.0003, ''buffer_size'': 1000000.0, ''env_name'': ''wealth_distribution'',
    ''init_exploration_policy'': 1000.0, ''n_epochs'': 3000, ''epoch_length'': 1000,
    ''update_cycles'': 10, ''target_update_interval'': 1, ''display_interval'': 1,
    ''batch_size'': 64, ''gamma'': 0.99, ''tau'': 0.005, ''eval_episodes'': 10, ''init_exploration_steps'':
    1000}}'
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.5
    start_time: 1679816863.741779
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.6.5
      5: 0.14.0
      8:
      - 5
